export const ActionTypes = {
    SET_HOME_PAGE_MOVIES: "SET_HOME_PAGE_MOVIES",
    SET_NOW_PAGE_MOVIES: "SET_NOW_PAGE_MOVIES",
    SET_SOON_PAGE_MOVIES: "SET_SOON_PAGE_MOVIES",
    SET_MOVIE_FOR_DETAILS: "SET_MOVIE_FOR_DETAILS",
};

Object.freeze(ActionTypes);
