export const ActionTypes = {
    SET_MAP_PAGE_SIDEBAR_VISIBILITY: "SET_MAP_PAGE_SIDEBAR_VISIBILITY",
    SET_THEATERS_POSSIBLE_FILTERS: "SET_THEATERS_POSSIBLE_FILTERS",
    SET_THEATERS_SELECTED_FILTERS: "SET_THEATERS_SELECTED_FILTERS",
    SET_MAP_DISPLAYING_THEATERS: "SET_MAP_DISPLAYING_THEATERS",
    SET_THEATERS_MAP_DEFAULT_VALUES: "SET_THEATERS_MAP_DEFAULT_VALUES",
};

Object.freeze(ActionTypes);
